### ISSUE TITLE
Can't extract files from archive back to an existing folder

### ISSUE THREAD

**Issue by frostbone25** [Telltale-Modding-Group/Telltale-Script-Editor#5]
After opening a TTARCH2 archive and deleting the unused files, one can't re-extract the files to the folder. You are prompted with "An archive with that name already exists within the project".

Solution: When opening a TTARCH2 archive, if a folder with the name already exists, create a temporary folder and instead extract the archive contents to the temporary folder instead. After extraction, move all of the contents back to the archive folder except for the files that share the same names. Then when that is complete simply just delete the temporary folder and its contents.

**Comment by violetfrost** [comment]
Won't fix this for 1.1 as it's intended but I'll experiment with alternate file importing methods for the 2.0 workflow.
